//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportProgramm.BaseDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Score { get; set; }
        public System.DateTime Date { get; set; }
        public string Place { get; set; }
        public int IdSport { get; set; }
    
        public virtual Sports Sports { get; set; }
    }
}
