//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportProgramm.BaseDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cup()
        {
            this.TournamentResults = new HashSet<TournamentResults>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Score { get; set; }
        public System.DateTime Date { get; set; }
        public string Place { get; set; }
        public int IdSport { get; set; }
    
        public virtual Sports Sports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentResults> TournamentResults { get; set; }
    }
}
