//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportProgramm.BaseDate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportProgrammProjectEntities : DbContext
    {
        public SportProgrammProjectEntities()
            : base("name=SportProgrammProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cup> Cup { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sport> Sport { get; set; }
        public virtual DbSet<Sportsman> Sportsman { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
