//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportProgramm.BaseDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sportman
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Team { get; set; }
        public string Lvl { get; set; }
        public int IdSport_1 { get; set; }
        public Nullable<int> IdSport_2 { get; set; }
        public Nullable<int> IdSport_3 { get; set; }
        public Nullable<int> IdSport_4 { get; set; }
        public Nullable<int> IdSport_5 { get; set; }
    
        public virtual Sports Sports { get; set; }
    }
}
