//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportProgramm.BaseDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sportsman
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Year { get; set; }
        public string Team { get; set; }
        public string LvL { get; set; }
    }
}
