//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportProgramm.BaseDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentResults
    {
        public int Id { get; set; }
        public int IdCup { get; set; }
        public int IdPlayer { get; set; }
        public Nullable<int> Position { get; set; }
        public string Score { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual Cup Cup { get; set; }
        public virtual Sportman Sportman { get; set; }

        public virtual Sportman Player { get; set; }
    }
}
